name: Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typescript:
    runs-on: ubuntu-latest

    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check types
        uses: yarn check:types

      - name: Run eslint
        run: yarn lint

      - name: Check formatting
        run: yarn format:chcek

  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      - run: uv sync --color always --locked
      - name: Run mypy type checking
        run: uv run mypy shittyserver.py stateserver.py
